### ISSUE TITLE
Text-Aktivität eingeben (UC 1)

### ISSUE THREAD

**Issue by siebermichael** [sweIhm/sweiproject-tg2a-1#1]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Studenten, Professoren und Administratoren können eine einfache Text Aktivität eingeben, die dann für alle sichtbar ist.
</td><td>
<ul>
<li>Button zum erstellen ist verfügbar
<li>Eingabefelder sind nach click auf den Button sichtbar und können bearbeitet werden
<li>Speichern Button ist in der erstellen Ansicht verfügbar
<li>Speichern von leeren Inhalten wird verhindert.
<li>Nach click auf speichern wird die Aktivität in der Datenbank gespeichert und für alle sichtbar
</ul>
</td></tr>
</table>

**Comment by salihuysal** [comment]
![aktivitatsdiagramm - textaktivitat eingeben](https://user-images.githubusercontent.com/32450514/33424439-26d12bfc-d5bc-11e7-9256-a6d8c567041c.jpg)
