### ISSUE TITLE
Aktivität anzeigen (UC 2)

### ISSUE THREAD

**Issue by siebermichael** [sweIhm/sweiproject-tg2a-1#2]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Als Gast möchte ich mir die Aktivitäten beider Hochschulen anzeigen lassen.
</td><td>
<ul>
<li>Übersicht aller Aktivitäten wird abgefragt und angezeigt.
</ul>
</td></tr>
</table>

**Comment by lallinger** [comment]
![aktvititaet_anzeigen_diagramm](https://user-images.githubusercontent.com/32633433/33451095-24e4cf2c-d60e-11e7-95ea-e576d7387447.PNG)
