### ISSUE TITLE
Aktivitäten aus Datenbank lesen (UC 2)

### ISSUE THREAD

**Issue by siebermichael** [sweIhm/sweiproject-tg2a-1#26]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Als Entwickler des Frontends möchte ich Aktivitäten aus der Datenbank lesen können. 
</td><td>
<ul>
<li> Get Anfrage (vom Client) kann vom Backend verarbeitet werden.
<li> Daten werden vom Backend aus Datenbank gelesen werden. 
<li> Daten werden vom Backend an Client zurückgeschickt.
</ul>
</td></tr>
</table>

**Comment by lallinger** [comment]
![whatsapp image 2017-11-24 at 12 22 13](https://user-images.githubusercontent.com/32633433/33208735-06622d92-d113-11e7-8611-e092708672b1.jpeg)
