### ISSUE TITLE
Aktivität in Datenbank speichern (UC 1)

### ISSUE THREAD

**Issue by siebermichael** [sweIhm/sweiproject-tg2a-1#27]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Als Entwickler des Frontends möchte ich Aktivitäten in die Datenbank speichern können. 
</td><td>
<ul>
<li> Post Anfrage (vom Client) kann vom Backend verarbeitet werden.
<li> Daten werden vom Backend in die Datenbank gespeichert. 
</ul>
</td></tr>
</table>

**Comment by flori-uni** [comment]
![image](https://user-images.githubusercontent.com/32478819/33375511-6dc495ba-d50a-11e7-9bf1-790cef37f094.png)
