### ISSUE TITLE
Aktivität in Datenbank bearbeiten (UC 8)

### ISSUE THREAD

**Issue by siebermichael** [sweIhm/sweiproject-tg2a-1#28]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Als Entwickler des Frontends möchte ich eine Aktivität in der Datenbank bearbeiten können. 
</td><td>
<ul>
<li> Update Anfrage (vom Client) kann vom Backend verarbeitet werden.
<li> Daten werden vom Backend in Datenbank angepasst.
</ul>
</td></tr>
</table>

**Comment by flori-uni** [comment]
![image](https://user-images.githubusercontent.com/32478819/33374551-f0b9df6a-d506-11e7-9b05-fd8414dfd8e1.png)
