### ISSUE TITLE
Aktivität in Datenbank löschen (UC 7)

### ISSUE THREAD

**Issue by siebermichael** [sweIhm/sweiproject-tg2a-1#29]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Als Entwickler des Frontends möchte ich Aktivitäten aus der Datenbank löschen können. 
</td><td>
<ul>
<li> Delete Anfrage (vom Client) kann vom Backend verarbeitet werden.
<li> Daten werden vom Backend aus Datenbank gelöscht.
</ul>
</td></tr>
</table>

**Comment by flori-uni** [comment]
![image](https://user-images.githubusercontent.com/32478819/33374361-23a40618-d506-11e7-8ee6-eddbf02142fe.png)
