### ISSUE TITLE
Emojis und Urls in Aktivitätdetails einfügen (UC 1 / UC 8)

### ISSUE THREAD

**Issue by siebermichael** [sweIhm/sweiproject-tg2a-1#34]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Als User möchte ich Emojis und Internetlinks in die Aktivitätsdetails einfügen. Durch das Anklicken der Links sollen die verlinkten Seiten erreichbar sein.
</td><td>
<ul>
<li> URL einfügen
<li> URL wird eingebunden
<li> Emoji einfügen
<li> Ansicht wird aktualisiert (URL's haben Highlighting, Emojis werden angezeigt)
</ul>
</td></tr>
</table>

**Comment by flori-uni** [comment]
https://github.com/Ledzz/angular2-tinymce
@salihuysal schau dir das mal an.

**Comment by flori-uni** [comment]
So das ist auch implementiert. 
Diagramm hierfür gibts nicht. Ist ja im Grunde nur eine Erweiterung des bestehenden Systems.
