### ISSUE TITLE
Text-Aktivität bearbeiten (UC 8)

### ISSUE THREAD

**Issue by lallinger** [sweIhm/sweiproject-tg2a-1#8]
<table>
<tr><td><b>User Story</td><td><b>Akzeptanzkriterien</td></tr>
<tr><td>
Jeder Student, Professor und Administrator kann den Text seiner eigenen Aktivitäten bearbeiten.
</td><td>
<ul>
<li>Anzeigen eines bearbeiten Buttons
<li>Nach drücken des Buttons wird eine Bearbeitungsansicht geöffnet
<li>Informationen können bearbeitet werden
<li>Speichern Button ist verfügbar
<li>Nach dem click auf den speicher Button werden die Informationen in der Datenbank und in der Ansicht aktualisiert
</ul>
</td></tr>
</table>

**Comment by salihuysal** [comment]
![textaktivitat bearbeiten](https://user-images.githubusercontent.com/32450514/33420652-af09734c-d5af-11e7-85e6-be81e64fd6da.jpg)
